project:
  type: website

website:
  title: "Adam Koplik Portfolio"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Projects"
        file: projects.qmd
      - text: "About"
        file: about.qmd
      - text: "Blog"
        file: blog.qmd
  page-footer: "© 2025 Adam Koplik"

format:
  html:
    theme: cosmo
    css: styles.css

resources:
  - projects/**