project:
  type: website
  output-dir: docs

website:
  title: "Adam Koplik Portfolio"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "About"
        file: about.qmd
      - text: "Projects"
        file: projects.qmd
      - text: "Feed"
        file: feed.qmd
  page-footer: "© 2025 Adam Koplik"

format:
  html:
    theme: cosmo
    css: styles.css
    highlight-style: dracula

resources:
  - projects/**