project:
  type: website
  output-dir: docs

website:
  title: "Adam Koplik Portfolio"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Projects"
        file: projects.qmd
      - text: "Feed"
        file: feed.qmd
  page-footer: "© 2025 Adam Koplik"

format:
  html:
    theme:
      light: flatly
      dark: cosmo
    toggle: true
    include-in-header: _site/_includes/navbar.html
    css: styles.css
    highlight-style: dracula

resources:
  - projects/**
