# Education: Neoliberalism\'s Next Victim
*Written for **EDUC-309: Education and Racialization** with Prof. Chenyu Wang on 3/13/2025*

The 1980s ushered in a global economic revolution, driven by the rise of
neoliberalism. The 1979 election of Margaret Thatcher as the United
Kingdom's Prime Minister in 1979, followed by Ronald Reagan's presidency
across the pond a year later, placed two of the world's superpowers
under hyper-conservative, free-market leadership. This decade saw a
shift toward trickle-down economics, marked by the vilification of
government intervention and the glorification of private industry.
Neoliberal politicians championed deregulation and corporate
empowerment, encapsulated by Thatcher's infamous quote, "*Economics are
the method. The object is to change the soul*". Neoliberalism asserts
that the government\'s role is to actively maintain the existence of a
market economy, a sentiment that has found its way into public
institutions, including education. By reframing societal success from
collective progress to an individual competition, these policies have
made everything quantifiable. As a result, a good education has
measurable with quantitative barometers for success just like a
business.

As neoliberalism promoted an individualistic culture, it embedded itself
into the structure of public education. Schools were reshaped to
function like a competitive marketplace, prioritizing producing
high-quality workers over equity and diverse learning. The 1983 report
*A Nation at Risk* was "the opening salvo of the neoliberal education
agenda" (Lipman, 46), marking the first of a wave of corporate-backed
reports that framed education as a tool for "U.S. economic
competitiveness and 'human capital development'" (Lipman, 46). These
reports approached education as a matter-of-fact, results-based
industry, looking to standardize public education to make it clear which
schools were succeeding and which were failing. In 2002, the neoliberal
agenda achieved its crowning jewel when the Bush administration passed
the No Child Left Behind law (NCLB).

NCLB mandated state-administered proficiency tests attached to
achievement standards as set by individual states. Schools were required
to show year-over-year improvement on these tests, with the threat of
disinvestment looming if they fell short of benchmarks. However, these
rigid mandates were implemented without accompanying policy measures to
support schools in meeting them. As a result, many districts failed,
creating "a narrative of unaccountable teachers and schools and
unresponsive and change-resistant public institutions" (Lipman, 46). By
placing blame on individual teachers, this approach ignored systemic
problems such as poor resource management, outside-community imposed
curricula, segregation, and broader structural poverty and racial
inequality.

The market-driven response of education was a focus on charter schools,
often staffed by non-unionized teachers allowing administrators to
easily punish educators they deemed inadequate and offer "merit pay" to
those who met their expectations. This transformed small and charter
schools into "instruments of the market" (Lipman, 47), representing
competition for the "status quo" of public schools. Corporate actors
began getting directly involved in the education system, embracing the
capitalistic assumption that competition breeds quality, further
entrenching neoliberal ideology in the public education sector.

One of the first great neoliberal experiments in education emerged in
the aftermath of Hurricane Katrina in New Orleans. Seeing opportunity in
disaster, President George W. Bush declared the Gulf Coast a "taxpayer
subsidized 'enterprise zone'", using the crisis to "implement the free
market fundamentalism that is not yet politically palatable in the rest
of the country'" (Lipman, 48). The city quickly restored tourist and
middle class areas while privatizing public services. The state-funded
gentrification of historically poor Black areas, seizing public housing
in these communities and converting it into market rate developments.

The final nail in the coffin for this shift came with the privatization
of the city's public schools. The state took control of 100 public
schools and transferred them to private organizations, and in the
process, "fired all 4,500 public school teachers, broke the city's
powerful Black-led teachers' union, and dismantled the school system's
administrative infrastructure" (Lipman, 49). In the years following
Katrina, the Department of Education invested over \$60-million to open
charter schools in Louisiana. Between 2006 and 2007, 31 of the 55 newly
opened schools in New Orleans were charter, compared to just five before
the disaster. This sweeping privatization effort was headed "by fiat by
the governor, guided by think tanks such as the Urban Institute and
backed by corporate foundations such as the Gates Foundation" (Lipman,
49). As a result, public school enrollment in New Orleans plummeted from
63,000 students before Katrina to just 24,000 afterwards.

The underlying goal of this reconstruction was clear: to create a
whiter, middle-class, more "capital and developed friendly" New Orleans
(Lipman, 50). This wasn't hidden, with the Director of Housing and Urban
Development Alphonso Jackson saying "New Orleans is not going to be as
black as it was for a long time, if ever again," (Lipman, 50). The
neoliberal advocates turned disaster into an opportunity to reshape
public education in favor of corporate interests.

Chicago's Ren2010 plan also advocated for a a neoliberal marketplace of
schooling. The original proposal was to replace 60 Chicago public
schools with 100 new ones, ⅓ charter, ⅓ contract, and ⅓ performance
schools-- schools operating under five-year performance contracts
contingent on meeting performance barometers. Following protests, the
city opted not to relocate students but instead replace all teachers and
administrators of schools that didn\'t meet their criteria.
Additionally, the city elected to consolidate and phase out low
enrollment schools on the grounds of improving "efficiency" and "cost
effectiveness" (Lipman, 51).

This created direct relationship between education and market, as "the
stage for Ren2010 was set by an accountability regime that normalized
labeling, sorting, and classifying schools, and meting out penalties
without regard for inequities in resources, opportunity to learn,
teachers' ideologies, cultural marginalization in curriculum and
instruction, the social context of the school, or the strengths children
bring to the school setting." (Lipman, 52). Ren2010 allowed the city to
easily classify schools as good or bad, and, instead of helping the
"bad" schools improve, allow the city to take them over and privatize
them.

However, the schools most at-risk were identifiable before the policy
came into practice. Decades of structural divestestment of these
institutions set them up to fail under this policy, resulting in
privatized education in low-income, minority communities compared to
selective enrollment public schools in gentrified areas. Public schools,
previously anchors for communities, were set to fail, with charter
schools recruiting their students, putting them at higher risk of losing
funding due to low enrollment. The overall goal of Ren2010 was clear:
the full-scale privatization of education.

Market-driven education has created competition not only between schools
but also students. As shown in *The Lottery*, students must compete in a
lottery for limited selection to charter schools. This results in a
self-fulfilling prophecy: those who get chosen receive a "good"
education, while the rest are resigned to underfunded public schools and
likely staying in poverty.

The Education Freedom Act, passed in Tennessee earlier this year, shows
this at play. The law established a scholarship program allowing
qualified students to receive vouchers to attend private school instead
of their zoned public schools (Kent). Rather than investing in improving
universal public education for all students, this system allows middle-
and upper-class students to benefit from either a strong public
education or to pay for private alternatives, while only the "best"
low-income students are honored with quality education.

Additionally, since the students that test well are the ones who get the
vouchers for private schools, they will leave struggling public schools
and further decrease the district's performance. This results in a
two-tiered education system based on a state-created market where
private schools are synonymous with quality, public schools with
failure, and little room for movement.

While market-driven education policies have commodified schooling,
they've also centered "good education" as productivity-centered. The
Trump administration has been at the forefront of this with its war on
Diversity, Equity, and Inclusion (DEI). The anti-DEI agenda is a two
front war with attacks based in both cultural and economic opposition.

Culturally, conservatives have framed DEI as a discriminatory practice
that simply blames White people for the world's problems and attacks
White identity. They take offense to any idea of America as a
structurally inequitable nation and view policies that address
fundamental inequalities between people as inherently anti-American. As
part of their anti-DEI movement, the Trump administration has sought to
attack schools that teach "divisive ideologies" and "indoctrination",
calling these teachings "illegal discriminatory practices at
institutions of learning." (*Schools...*).

Economically, conservative policy makers have framed their opposition to
DEI in a way that appeals to the neoliberal, establishment base that
Republicans have formed since Reagan. At its core, they argue, DEI is an
unproductive learning style. They contest that social sciences and
humanities are not tangible, skill-based topics and do not improve
students' ability to compete in the job market. Contrastly, STEM and
business curricula promote valuable skills that can immediately give
students the leg up on their peers and create more productive workers.
For those who struggle with STEM or business classes,
vocational-technical schools---offering direct job training in trades
like electricity and plumbing---are the next best option.

The late comedian George Carlin captured this sentiment: "They don't
want well informed, well educated people capable of critical
thinking...They don't want people who are smart enough to sit around a
kitchen table to figure out how badly they're getting f--ked by a
system...They want obedient workers" (Goodreads). Identifying America's
systemic failures does not create more jobs, but threatens the
neoliberal economy and is inherently inefficient.

While DEI faces resistance, neoliberalism selectively embraces diversity
when it can be used. Diversity as a commodity that can be monetized and
marketed rather than a lived experience is an incredibly valuable tool
for neoliberal education. The University of Texas Rio Grande Valley
positioned itself as the first bilingual university. They promoted the
Spanish language as an economic asset that can be commodified instead of
a cultural identity held by human beings. This practice of converse
racialization rebranded the language as a neutral tool, not linked with
any group of people, aligned with market values. It inherently shifted
language from being a cultural expression to a tool for economic
competition. (Mena & Garcia).

As neoliberalism shapes education policy, the consequences of treating
schools as corporations become clear. A fully marketized and privatized
education system will mirror the modern economy: one of deep inequality,
where those born into privilege receive quality education and only the
luckiest few achieve social mobility. Thatcher's assertion that,
"Economics are the method. The object is to change the soul" will have,
in turn, been realized.

Neoliberalism has spent the past half-century casting private
corporations as the bastions of progress and the government as standing
in the way of the future. It has transformed the public perception of
government from something that should uplift and provide a foundation
into something that should operate with efficiency. Housing, labor
unions, and environmental protections have already fallen in the name of
the free-market, and education is just the next frontier in this
cultural and economic takeover.

This is no longer just a political issue; but a cultural reckoning.
Without a radical change to the way Americans perceive the government's
role and movement from neoliberalism's manufactured measures of success,
America will continue to move further from the meritocracy neoliberals
pretend we have and into the oligarchy their actions have constructed.

**References**

Goodreads. (n.d.). *A quote by George Carlin*. Goodreads.
https://www.goodreads.com/quotes/964648-but-there-s-a-reason-there-s-a-reason-there-s-a-reason

Kent, B. (2025, January 31). *The Education Freedom Act has passed, how
does it work?*. WBBJ TV.
https://www.wbbjtv.com/2025/01/30/the-education-freedom-act-has-passed-how-does-it-work/

Lipman, P. (2011). *The New Political Economy of Urban Education:
Neoliberalism, race, and the right to the city*. Taylor & Francis.

Mena, M., & García, O. (2020). 'converse racialization' and 'un/marking'
language: The making of a bilingual university in a neoliberal world.
*Language in Society*, *50*(3), 343--364.
https://doi.org/10.1017/s0047404520000330

*Schools should be focused on learning.* Department of Education Form.
(n.d.). https://enddei.ed.gov/

Wikimedia Foundation. (2024, November 11). *The lottery (2010 film)*.
Wikipedia. https://en.wikipedia.org/wiki/The_Lottery\_(2010_film)
