# The Second Cold War: An Analysis of US-China Relations**
*Written for **GOVT-114W: International Relations** with Prof. Alan Cafruny on 5/11/2023*

**ABSTRACT*:*** *The US and China are on the brink of a Second Cold War.
With China's economic and global political power growing by the day,
decades long American unipolarity is under threat. In this essay, I will
show that, while there are strategies the US could pursue to contain
China, they are not as beneficial as an allyship with the nation would
be.*

On November 9, 1989, the Berlin Wall fell. This marked the end of the
decades long Cold War between the United States and the Soviet Union and
the beginning of American unilateral dominance. For the ensuing decades,
the US maintained a stranglehold over the rest of the world, with no
worthy competitor appearing. It wasn't until the Obama administration's
"Pivot to Asia" that the threat of China on American hegemony was really
taken seriously. Now, the question is presented: can the US hope to
contain China? While there are strategies that could be implemented to
achieve this containment, the economic and global stability risks
associated with them are not worth it.

Richard Nixon's visit to China marked an unprecedented turning point in
US-China relations. It created the beginning of a partnership between
two of the world's largest nations--one that reaped benefits for both
sides. The US viewed China as a location for use cheap labor and lesser
regulations to bolster US companies and increase US technology. On the
other hand, China viewed the US as a nation that it could use to
increase its global power--which is exactly what it did, using its role
as a manufacturing haven to bolster its economy and become one of the
worlds largest markets. This marked the beginning of a strong
interdependence between the two nations, with China becoming "America's
biggest supplier of imported goods and its top source of international
students, while the United States is now China's number one export
destination and its most important foreign financial partner" (Bateman).
This relationship was without issue for a long time, but now, the US
sees China's power as growing too much to the point of threat.

The official American shift as it relates to China came during the Obama
administration's "pivot to Asia". The administration increased military
and economic relations with Vietnam, South Korea, and Japan, among
others, looking to prevent Chinese unilateral power on the continent.
This came as China was prepping to overtake the US as the world's
largest economy which happened in in 2014, when "the International
Monetary Fund announced that, when measured in terms of purchasing power
parity, China had passed the United States...Measured by market exchange
rate, China's GDP is now nearly 70 percent of the United States'"
(Layne). This key shift represented the beginning of what would soon
become an all out economic war between the two nations, and the
beginning of a Second Cold War.

Donald Trump ran for President on the basis of ultranationalism that
found itself often pointing in China's direction. With the loss of the
American middle class and manufacturing jobs, many of which fleeing to
China, Trump tugged at the anger of Americans who felt left behind and
wanted an enemy. He made China that enemy, and, when elected, put in
place massive economic restrictions against China. The most important of
these was probably the strict tariffs put in place by the administration
in its early days. China retaliated with tariffs of their own targeting
US farmers and manufacturing workers. Additionally "Export controls
targeting China were greatly intensified, most notably via the
Department of Commerce's Entity List that restricts foreign companies
from importing U.S. products. The number of unique Chinese firms on this
list quadrupled from 2018-2022" (Layne). These policies led to "the
Chinese foreign ministry proclaim\[ing\] that the United States had
started 'the largest trade war' in history" (Cafruny).

Under the Biden administration, it has been more of the same. The
anti-China rhetoric and policies that were prevalent under Trump
continued in an increasingly bipartisan manner. While Biden moved away
from some of the more xenophobic and strawman arguments made under
Trump, like the talk of banning TikTok just for Chinese association, he
replaced it with stronger policy. His administration has continued
fighting the economic war, filling in "some important gaps --- requiring
proof, for example, that imports from Xinjiang weren't made with forced
labor" (Bateman).

At the heart of the Chinese-American economic war sits semiconductors.
Semiconductors are the main ingredient in a ton of revolutionary
technology including electric cars and will be the most important
resource in the world over the coming decades. Currently, neither of the
two nations are overwhelmingly producing their own semiconductors. China
sits ahead of the US who have responded by creating massive sanctions on
China to try to avoid the expansions of Chinese semiconductor
manufacturing. The US has begun trying to involve Japan and South Korea
in the semiconductor supply chain, as well as the all important Taiwan.

So, who is winning this second Cold War at this point? China is
certainly not in their best state, with "China...experiencing a host of
serious problems including massive surplus capacity, mounting debt now
at 260% of (officially declared) GdP and problems in the "belt and Road"
project designed in part to export surplus capacity...China's growth
rate has steadily declined" (Cafruny). Still, while China is not
thriving, the US-Chinese interdependence is still high. "Interdependence
is everywhere you look, from semiconductors (the U.S. chip industry gets
one third of its revenue from China) to manufacturing (China is a
critical hub for companies like Apple and Tesla) to science (Chinese and
American scientists author more joint papers than any other country
pair)" (Bateman).

To this point, no one is winning the economic war. However, that doesn't
mean one of the two won't eventually move ahead. Which presents the
question: is any of this worth it? Is American hegemony really worth
destroying the relationship between the US and possibly their strongest
economic partner? More importantly, is it worth potentially putting
lives on the line to further America's stance in the world?

In Layne's "Coming Storms", he draws intense parallels between the
current US-China situation and that between Germany and Britain during
the 1910s. Both situations saw fast growing nations come to a head with
the current unilateral world power. Then, it resulted in the partial
destruction of the European continent. Now, it would likely see violence
fought over Taiwan. Taiwan, the source of 90% of semiconductor
manufacturing, represents a tense argument between the two nations.
While in the past the US has respected the "One China" policy and
refused to recognize Taiwan as a sovereign nation, more recently the US
has pulled back on these methods. US leaders like Nancy Pelosi have
visited the nation, and Taiwanese leaders have visited America. China
has responded with shows of force like bomb tests. It seems as though
the US is trying to bait the Chinese into a war, and more than likely,
Taiwan will be the place of fighting. The Taiwanese don't believe the
semiconductor question can be decided via violence however, with the
chairman of Taiwan Semiconductor Manufacturing Company saying, "Nobody
can control TSMC by force. If you take a military force or invasion, you
will render TSMC factory non-operable, because this is such a
sophisticated manufacturing facility \[that\] it depends on the
real-time connection with the outside world --- with Europe, with Japan,
with the US."

The US and China currently find themselves embroiled in what many
consider to be the second Cold War. While we managed to survive the
first one without global catastrophe, there were several close calls. In
the movie \"13 Days,\" a character states that \"If the sun comes up
tomorrow, it is only because of men of good will. That is all there is
between us and the devil.\" This illustrates just how close we were to
annihilation and how much we relied on the kindness of others to prevent
it. Unfortunately, it seems we are on a path that could lead us back to
that brink. Hypothetically, the US has the power to engage in both
physical and economic warfare to contain China, but it would come at an
immeasurable cost. The better path forward is one of bilateral support
between the two most powerful nations in the world. It\'s possible for
the US and China to exist in competitive harmony without resorting to
violence or death. While this will require individuals of good will to
come together, it is the most viable option for a peaceful and
prosperous future.

**Works Cited**

Bateman, Jon. "Opinion: The Fevered Anti-China Attitude in Washington Is
Going to Backfire." POLITICO,
www.politico.com/news/magazine/2022/12/15/china-tech-decoupling-sanctions-00071723.
Accessed 11 May 2023.

Cafruny, Alan. "Can the United States Contain China?" Russia in Global
Affairs,
eng.globalaffairs.ru/articles/can-the-united-states-contain-china/.
Accessed 11 May 2023.

Layne, Christopher. "Coming Storms." Foreign Affairs, 23 Feb. 2023,
www.foreignaffairs.com/articles/united-states/2020-10-13/coming-storms?utm_medium=promo_email&amp;utm_source=lo_flows&amp;utm_campaign=registered_user_welcome&amp;utm_term=email_1&amp;utm_content=20230510.
