# Dying for Capitalism: An Analysis of Marxism
*Written for **GOVT-114W: International Relations** with Prof. Alan Cafruny on 2/15/2023*

**ABSTRACT:** *Marxism is one of the most important breakthroughs in
international policy, turning the mirror back on the state themselves.
This paper investigates the philosophical and historical beginnings of
the theory, then uses events as evidence of the theory. It also breaks
down the strengths and weaknesses of Marxism, applying these with direct
examples.*

Today, Marxism represents much more than an economic theory. Right wing
politicians have made it their mission to incorrectly label their
dislikes as Marxist. Whether it be social security, the teaching of
American racism, or the new M&M mascots. But before it was a buzzword,
Marxism was a strong international relations theory used to critically
analyze foreign policy decisions. The basic premise of Marxism is that
states make policy decisions based on expansionary, capitalist ideals.
Examples of state action under these pretenses exist throughout
capitalist history, including the American interventions in Iraq, Iran,
and Ukraine, as well as the current US-China rivalry.

The philosophical origins of Marxism are tied to its original economic
basis. As capitalism spread across the world after the British
industrial revolution, a rival economic theory came into play. Economic
Marxism is predicated on the idea of a revolution resulting in workers
taking over and controlling the means of production. Marxism says that
the fundamentals of capitalism will inevitably lead to massive class
inequality and, eventually, a communist revolution. While Marx himself
was much more focused on the actions within states than interstate
relations, he did apply his theory to world connections at points.

Marxism as an international relations theory argues that interstate
rivalry is rooted in the expansionary ideals of capitalism. It refutes
the weather-vane theory that states actions are pushed by interest
groups, with the state itself being a neutral actor. Instead, Marxism
argues that the state is structurally controlled by the capitalist
ruling elites, so therefore the state itself is an actor. The "best
interests" of the state will always be the best interest of the elite
and it will make its decisions on this basis. The only way to end this
rule is via a revolution that systematically changes the state into a
socialist society. Marxism argues that the actions of states are not
simply an end, but a means to capitalist expansion.

The international relations theory that most staunchly diverges from
marxism is liberalism. Liberalism is based on a global free market,
arguing that once economic integration occurs across the world, an
international community can be created and conflict will be avoided due
to economic reliance. The modern day situation in China is a prime
example of the differences in theory. While trade between the nations is
robust, the United States recently clamped down on the exportation of
semiconductors to Chinese customers to prevent the spread of the
technology. Many consider this an act of economic warfare and tensions
between the nations have continued to grow. Liberals would argue war is
being avoided because capitalism is keeping the peace. They would look
at the shared reliance on trade and say that the United States and China
will never go to war, because it would risk their economic prosperity.
Marxists would argue the opposite. They would look at the world's two
largest economies and note that their current rivalry is rooted in
capitalism. Modern capitalists need global trade, which inherently leads
to global economic rivalry. Capitalism doesn't have a ceiling.
Capitalists have a constant goal: accumulate, accumulate, and accumulate
more. In that vein, Marxists would look at the United States-China
situation and argue that war is inevitable.

One of the most formative events in the spread of Marxism as
international relations theory was the United States' intervention in
Iran in the 1950s. Between 1901 and 1952, British owned Anglo-Iranian
Oil Company enjoyed a monopoly on Iranian oil. In 1951, Mohammed
Mossadegh came into power in Iran, expelling the AIOC and nationalizing
Iranian oil. In response, the British attempted and failed a coup,
leading to the nation inquiring with newly elected US President Dwight
Eisenhower about possible US involvement. Eisenhower's secretary of
state, John Foster Dulles, "had two lifelong obsessions: fighting
Communism and protecting the rights of multinational corporations".
Knowing this, the British misled Dulles that Mossadegh was pushing Iran
toward Communism. The US, pusheed by American oil companies, staged a
coup. After a few attempts, the US eventually overtook Mossadegh,
bringing in authoritarian General Fazlollah Zahedi (Kinzer). The actions
of America in Iran can be used to support a Marxist view of foreign
policy, as the government acted in opposition to democratic ideals to
overthrow a free government and raise their own stature as an oil king.

The strength of Marxism lies in the historical decisions made by
nations. The most infamous foreign policy disagreement in the 21st
century is the Iraq War. Different theorists have different theories as
to why the war was fought. Liberals believe it was to restore United
Nation authority and promote human rights in the region. Realists often
follow the official American arguments that Saddam Hussein was a threat
to world stability and held weapons of mass destruction. Marxists
however, promote one of the more controversial arguments: the war was
fought to gain oil access in the region and to promote the global
capitalist order (Cafruny).

At the time of the war, the US had been looking for a chance to
consolidate their power in the region. A little over a decade prior, an
indebted Hussein had invaded Kuwait to drill for oil, sparking the Gulf
War. While the US invasion of Iraq was declared legal under the facade
of saving the people of Kuwait, it is not a reach to suggest that the US
only entered the war to solidify their control over the Kuwaiti oil
supply. After the war ended, Hussein began making oil deals with Russia,
Germany, France, China, and other nations. American oil companies,
nervous about losing their customers, pushed the Bush administration to
come up with a solution. They did, and the United States invaded Iraq
after, according to the Center for Public Integrity, "an orchestrated
campaign that...led nation to war under decidedly false pretenses"
(NPR). As argued by Cafruny, "The Iraq war was fought to reverse the
decline of American international oil companies (IOCs) relative to
state-owned national oil companies (NOCs) in the Middle East and their
less disciplined clients in Europe and Asia, while improving the
position of the American IOCs in the struggle for wealth and power."
(Cafruny). American oil companies were desperate for more control in the
region, and the invasion of Iraq gave them an excuse.

In modern day, the strengths of Marxist theory can be applied to the
current Russia-Ukraine war. The United States, while feigning morality,
continues to push for the war as a means of weakening Russia. America is
fighting a war with Ukranian bodies, and Marxists would argue that a
significant factor in the current war was the Russia-Germany gas
pipeline. The US has been attempting to end this pipeline so they could
begin selling natural gas to Germany for years, and construction on a
new one, Nord Stream 2, had begun. At the war's beginning, the US
pressured Germany to punish Russia's illegal invasion by cutting off the
pipeline. Germany abided, but the pipeline was still "mysteriously"
destroyed at the beginning of the war. Investigative journalist Seymour
Hersh reported evidence that the US had involvement in the pipeline's
destruction, something that was heavily speculated but not confirmed.
The demolition of the two Nord Streams allowed for Germany to worry less
about increasing their own tensions with Russia, and has led to more
German reliance on American gas companies.

In general, for strengths and evidence of Marxism, look no further than
the Cold War. Every foreign policy decision made by America during the
period was made with the intention of spreading the global capitalist
order. The Vietnam and Korean wars, their backing of Osama bin Laden in
the Afghan War, and the countless coup d\'etats they orchestrated all
looked to push capitalism. While disguised under "spreading democracy",
the replacing of democratically elected leaders in Chilé and Iran with
authoritarians shows that the US would prefer a fascist, capitalist
world order than a free, leftist one.

On the other hand, Marxism can have some weaknesses. A key error in its
development is the assumption of rational actors in power. Since
Marxists believe that the state is not a neutral actor and instead
structurally created to support the elite, then the decisions of the
state should have this same intention. However, some leaders are not
rational. Even if there is a "correct" decision to gain that nation
economic power, leaders may make different choices based on irrational,
moral, or greater political reasons. For example, the US recently
affirmed the election of new leftist Brazilian President Luiz Inácio
Lula da Silva, who defeated right wing leader Jair Bolsonaro. After the
election, there was a raiding of the Brazilian capital building a la
January 6 in the US. America's Democratic leaders called the election
free and fair, something they rarely do with leftist leaders. The reason
they would do this is because at this point it is more politically
beneficial for Joe Biden to have a leftist running Brazil than it would
be to position himself next to right winger Bolsonaro in today's
political climate.

Marxism is not an extreme idea. It is not this boogeyman like many in
American politics try to paint it as. To critique capitalistic
structures does not make one a radical, and to unbiasedly view the
policy decisions made by capitalistic nations does not make one a
leftist. Marxism is a strong international relations theory, and it is
past time the world began accepting it as it once did.

**Works Cited**

Cafruny, Alan, and Ted Lehmann. "IMPERIALIST RIVALRY AND THE INVASION OF
IRAQ."

"Group: \'Orchestrated Deception\' by Bush on Iraq." *NPR*, NPR, 23 Jan.
2008,
https://www.npr.org/2008/01/23/18319248/group-orchestrated-deception-by-bush-on-iraq

Kinzer, Stephen. *Overthrow: America\'s Century of Regime Change from
Hawaii to Iraq*. Times Books/Henry Holt, 2007.

Seymour Hersh. "How America Took out the Nord Stream Pipeline." *How
America Took Out The Nord Stream Pipeline*, Seymour Hersh, 8 Feb. 2023,
https://seymourhersh.substack.com/p/how-america-took-out-the-nord-stream.
