# Start from Scratch: Analyzing the Replacement of NAFTA with the USMCA
*Written for **GOVT-114W: International Relations** with Prof. Alan Cafruny on 5/11/2023*

**ABSTRACT*:*** *The North American Free Trade Agreement was a
groundbreaking agreement between its three members. Now, 30 years later,
it has been ripped up and replaced. In this essay, I will analyze the
pros and cons of NAFTA and show that the USMCA represents a massive step
forward.*

Nearly three decades ago, the United States, Canada, and Mexico took a
bold step towards economic integration by signing the North American
Free Trade Agreement (NAFTA). It was a groundbreaking move that united
two of the world\'s most developed nations with a rapidly developing
neighbor, creating a powerful trade bloc. But despite its ambitious
goals, NAFTA fell short of expectations and became a hotly debated topic
among politicians in all three countries. It\'s no surprise that the
Trump administration sought to negotiate a new deal, the
US-Mexico-Canada Agreement (USMCA), to replace NAFTA. In hindsight,
it\'s clear that NAFTA had a negative impact on both the US and Mexico.
The USMCA is a welcome step forward that will create new opportunities
for businesses and workers alike, bringing us one step closer to a truly
integrated and prosperous continent.

In 1993, the Clinton administration signed the controversial NAFTA
agreement, a first of its kind. "NAFTA eliminated most tariffs on
products traded between the three countries, with a major focus on
liberalizing trade in agriculture, textiles, and automobile
manufacturing. The deal also sought to protect intellectual property,
establish dispute resolution mechanisms, and, through side agreements,
implement labor and environmental safeguards" (Chatzky, et al.). The US
and Canada hoped that NAFTA would lead to a stronger Mexican economy,
which would in turn become a location for low cost labor. Overall, NAFTA
is seen by many economists as a wash. \"NAFTA did not cause the huge job
losses feared by the critics or the large economic gains predicted by
supporters. The net overall effect of NAFTA on the U.S. economy appears
to have been relatively modest,\" per the Congressional Research Service
(Geewak).

Still, NAFTA was not without its benefits for both US and Mexico. From a
purely neoliberal outlook, trade more than tripled between the three
nations with Canada and Mexico ranking as the top two nations for US
exports. For the US, North America has appeared as a strong market for
manufacturing vehicles, "...so when you are buying a vehicle assembled
in Canada, it contains lots of made-in-America parts" (Geewak).
Additionally, the US has seen a trade surplus of almost \$30-billion
under NAFTA.

For Mexico, there was a massive increase in agricultural imports after
NAFTA. While this has its flaws, it made the country less reliant on
their own farm based economy which was more variable to weather events
and such. Additionally, it has resulted in an overall increase in wealth
for the nation. Mexico has developed very fast and has seen growth from
its middle class.

On the other hand, critics of NAFTA have a ton of ammunition. One of few
things agreed by both Donald Trump and Bernie Sanders was that NAFTA has
led to a loss of US manufacturing jobs. The Economic Policy Institute
found that US workers have lost almost 700,000 jobs specifically to
Mexican rivals. However this is far from a zero sum game, "while
millions of U.S. manufacturing jobs have melted away over the last two
decades, economists attribute most of those losses to new technologies
and Asian competition, not NAFTA" (Geewak). NAFTA's almost complete lack
of labor rights or protections for American workers was a massive
oversight that put the growth of the global capitalist economy over that
of actual workers.

For Mexico, NAFTA was pretty much a disaster. Mexican President Carlos
Salinas de Gortari believed NAFTA was a chance to "modernize the Mexican
economy so that it would 'export goods, not people'". While it did see
growth in its exports and trade, Mexican workers didn't reap the
benefits. "Poverty remains at the same levels as in 1994. And the
expected convergence of U.S. and Mexican wages didn't happen, with
Mexico's per capita income rising at an average of just 1.2 percent
annually in that period..." (Chatzky, et al.).

The biggest negative impact to come out of NAFTA came with the change of
food production. As put by Carlsen, "economic efficiency dictates that
each country should devote its productive capacity to what it does best
and trade liberalization will guarantee access across borders. trade
liberalization." At the time it was signed, corn was the biggest
resource to be developed by Mexican farmers. However, since its yields
were significantly below that of the US, Mexican farmers stopped being
able to compete with the imported corn and were not backed by their
government, instead being told to find jobs in manufacturing, since that
was going to be Mexico's main role in NAFTA. What ensued was a corporate
takeover of the Mexican food system, leading to increasing unemployment,
lower health standards for their food (Mexico has the second worst
morbid obesity rate behind the US), and an exodus of jobless Mexicans to
the US to try to find work. While the more industrialized north saw some
betterment compared to the agricultural south, "the areas that adapted
successfully to industrial agriculture and agroexport crops are
characterized by flagrant violation of the labor rights of migrant farm
workers, widespread pollution and water waste, and extreme concentration
of land and resources" (Carlsen).

For both the US and Mexico, the US-Mexico-Canada agreement was a
necessary step forward in trade negotiations and the world economy. It
addressed issues surrounding labor protections, jobs in the US, and
environmental rights. One of its stronger stipulations was the demand
that 75% of vehicles assembled in a nation must originate in the member
countries. This avoids outsourcing parts to non-member countries and
ensures more manufacturing jobs stay. Another key addition made is the
stipulation that 40% of each vehicle must come from factories paying at
least \$16 an hour. This small but strong addition endorses better labor
rights and help for workers who were overall left behind by NAFTA. It
also requires more Mexican recognition of unions and collective
bargaining agreements, measures to combat illegal fishing and wildlife
trafficking, and the extension of patent protections for certain drugs.
In comparison to NAFTA, USMCA is a massively more worker based agreement
that, while not without its faults, is a massive step forward (Chatzky,
et al.).

NAFTA was a disastrous agreement that caused more harm than good.
Despite promises of economic growth and job creation, it resulted in a
meager increase in GDP while sacrificing thousands of American and
Mexican jobs. As if that wasn\'t bad enough, it also exacerbated
inequality in Mexico and created a \"profoundly unhealthy food system
for the entire \[Mexican\] region\" (Carlsen). This agreement was a slap
in the face to workers and prioritized expanding the global capitalist
order above all else. It was a complete failure that demanded immediate
attention. Thankfully, the USMCA is a step in the right direction,
placing a greater emphasis on workers\' rights than most US trade
agreements. However, there\'s still much work to be done. The massive
globalist trade will always leave domestic workers at risk, and member
economies must prioritize the well-being of workers over the pockets of
the elite. The USMCA must be used as a catalyst for positive change, a
starting point for the creation of a fairer, more equal trade system
that empowers workers and brings prosperity to all members of society.

**Works Cited**

Carlsen, Laura. "NAFTA Is Starving Mexico - FPIF." Foreign Policy In
Focus, 9 May 2013, fpif.org/nafta_is_starving_mexico/.

Chatzky, et al., Andrew, et al. "NAFTA and the USMCA: Weighing the
Impact of North American Trade." Council on Foreign Relations, 1 July
2020, www.cfr.org/backgrounder/naftas-economic-impact.

Geewax, Marilyn. "Economists Toast 20 Years of NAFTA; Critics Sit out
the Party." NPR, 8 Dec. 2013,
www.npr.org/2013/12/08/249079453/economists-toast-20-years-of-nafta-critics-sit-out-the-party.
