# Skull Valley Band Nuclear Dump: Tribal Sovereignty's Role in Environmental Justice
*Written for **ENVST-392: Decolonizing the Anthropocene** with Dr. Brianna Burke on 5/13/2025*

In late 1996, the Skull Valley Band of Goshute Indians Reservation entered into a lease agreement with Private Fuel Storage (PFS) to host a nuclear waste dump on the Skull Valley Goshute Indian Reservation in Utah. That's the headline. For the nuclear conglomerate PFS and the U.S. government, that was more than enough to move forward. The problem? Skull Valley Tribal Chairman Leon Bair signed the agreement without the tribe's General Council knowing or approving of the deal. The monetary amount agreed upon was never disclosed--to this day, "no tribal member outside the three member tribal executive committee knows..." (Kamps, 2001). After decades of legal fights, the project was halted. The case is an incredibly interesting investigation into the role of tribal sovereignty in environmental justice and the economic injustices that inform their decisions.

At the time of the agreement, just 25 tribe members actually inhabited the reservation. The other 100 or so Band members lived a bit closer to
Salt Lake City. The displacement out of this group was no accident, but
a series of environmental destruction that brought about the inhabitant
dispossession of their land. Surrounding the reservation is the
Magnesium Corporation--the "nations worst air polluter" (Kamps, 2001)
that has brought about chlorine gas, acid clouds, and hazardous
landfills. In 1968, Dugway Proving Grounds testing of VX nerve gas
resulted in the "accidental" death of 6,400 sheep in Skull Valley. On
top of this, half of the US Army chemical weapon stockpile is burning in
a nearby incinerator and the local Air Force base is dropping bombs,
misfiring missiles, and crashing jets all in the surrounding area. This
concerted effort from both the government and corporations has resulted
in an inhospitable economy for the tribe. Leon Bear, the chairman who
signed the dump deal in 1996, said "We can\'t do anything here that\'s
green or environmental. Would you buy a tomato from us if you knew
what\'s out here? Of course not".

Clear parallels exist between the story of the Skull Valley Band and
that of the characters in Ann Pancake's *Strange As This Weather Has
Been*. Similarly, the Appalachian characters have seen their home's
health systematically attacked by corporations looking to exploit the
land for profit. The coal mining industry and the nuclear industry--seen
as rivals by the average American environmentally--are two sides of the
same coin when it comes to the exploitation of people. As a result of
the environmental destruction of these areas came their economic
demolition. Both the Skull Valley Band and the Appalachian people in
*Strange As...* suffer from massive unemployment and high poverty rates,
making them easy targets for the large companies to dispossess them from
their lands. These companies create the illness (poverty) so they can
sell the disease (money for land).

The reason the Skull Valley case is so interesting is that it's not
simply a case of the United States government violating a treaty. It is,
however, a clear case of environmental injustice. Yes, the contract was
signed by the Band's tribal chairman. However, it was clear and obvious
why the Goshute were targeted--they're an incredibly small, impoverished
tribe that would be easy to manipulate in the eyes of a corporation.
Yet, even justice has a price. In 2000, the U.S. Nuclear Regulatory
Commission deemed that the dump does not violate environmental justice
because PFS's price was so high. Additional agreements were made between
PFS and local opposition like cattle ranchers and Tooele County in the
years after to get the dump moving forward. Utah Governor Mike Leavitt
put it bluntly, saying, "It's pretty clear that utilities are willing to
spend billions to move the spent fuel out of their back yard into ours."

The case is a prime example of the cheapening discussed in Jason Moore
and Raj Patel's "A History of the World in Seven Cheap Things: A Guide
to Capitalism, Nature, and the Future of the Planet". Colonialism's
devaluation of nature and people in the name of productivity is a clear
cycle that seems inescapable, valuing "only what it \[capitalism\] can
count, and it can count only dollars" (Moore & Patel, 2021, p. 21). This
cheapening begins at the changing of one singular letter: Nature vs.
nature. Capitalism has created this naturalization of ecology as a
resource to be turned into production. It has formed an imaginary
hierarchy where Society is the boss of Nature and can control Nature to
its whims. In this, human beings are also brought into the folds of
Nature, with Indigenous peoples not being considered members of Society
and therefore being disposable and able to be exploited. The actions of
PFS are a clear example of this. Not only do they want to use the
natural world as a dumping ground for toxins, showing a complete apathy
for the non-human life that inhabits the area, but they want to use the
tribe members themselves to do their bidding for them. This creation
infighting of oppressed people is a classic maneuver used by oppressors
to distance themselves from the problems they're creating.

To see this shift of blame one had to look no further than the Skull
Valley Band's own website. A quote from scientist Marie Curie, "Nothing
in life is to be feared. It is only to be understood", was plastered
along with arguments for why nuclear science is safe and a good economic
decision for the tribe. The argument for the lease was being made by
tribe members themselves. This inviting of Native nations into
exploitative economic partnerships was coined by Randel Hanson as, "new
Indian capitalism" (Hanson, 2001, p. 25). Tribal sovereignty and
economic independence have been pitched as one and the same. The
argument from neoliberal colonialists is clear: if tribes want freedom,
they have to be able to afford it. This economic partnership mirrors
other exploitative ones, "Housing these forms of garbage on reservations
'off-shores' it in a way not dissimilar to...locating factories in
underdeveloped nations" (Hanson, 2001, p. 32). The proposals shape
themselves as allowing sovereignty, but asks them to participate in the
same activities that took it away in the first place. Margene Bullcreek,
an avid opposer of the dump, put it bluntly: "Sovereignty isn't selling
your independence and your heritage to the highest bidder" (Kamps,
2001).

The consequences of this are explored in Kyle Whyte's "Indigenous
Climate Change Studies: Indigenizing Futures, Decolonizing the
Anthropocene". Members of the Skull Valley Band don't actually have a
say in the use of their land. They're told to choose between bad and
worse, and then have it made out to seem like they agreed to whatever
consequences they suffer. Indigenous peoples have become the vicitm's of
a cultural genocide that makes it seem as though the problems they face
are their own doing. Whyte discusses this, saying "Indigenous peoples
live in worlds so changed by colonialism, capitalism, and
industrialization that our collective self-determination and agency are
compromised" (Whyte, 2017, p. 160).

By coating environmental injustice in the disguise of economic
opportunity, corporations are profiting off of the problems they've
already caused. Tribal chairman Leon Bear, who had agreed to the
contract, said "People need to understand that this whole area has
already been deemed a waste zone by the federal government, the state of
Utah and the county" (Ishayam & TallBear, 2001, p. 5). This erie view of
the situation puts into perspective why Bear made the decision he did.
The tribe had already been written off entirely, and the area was seen
as a waste zone. The only way out, Bear believed, was by embracing the
colonial actions that have brought so much destruction in the past. As
Whyte discussed, this line of thinking is an example of how Native
people have survived an apocalypse, saying "Native Americans have seen
the end of their respective worlds" (Whyte, 2017, p. 160). The "New
Indian Capitalism" is a direct symptom with the destruction of Native
civilization and knowledge.

So what can be done? Ishiyama and TallBear critique the narrow view of
environmental justice, saying, "This paper challenges the predominant
tradition of environmental justice scholarship and activism that focus
on the inequitable distribution of hazards in low-income minority
communities" (Ishiyama & TallBear, 2001, p. 1). Framing environmental
justice activists as only opposing the economic opportunities presented
to them undermines the members of the tribes themselves, assuming that,
"Indians lack the intelligence to balance and adequately protect their
own economic and environmental interests" (Ishiyama & TallBear, 2001, p.
2). They argue that the white environmental justice approach ignores the
participants, only focused on the results of the decision and not the
process. White activists support tribes conditionally, only accepting
those that conform to their own environmentalist beliefs and disparaging
those that do not. They position internal struggles as "occurring
between morally pure 'traditionalists' and less moral 'assimilationists'
(Ishiyama & TallBear, 2001, p. 2). This then posits the assimilationist
leaders as colonial sympathizers who are exploiting their own people,
ignoring the environmental racism and oppression that has impacted
whatever decision they're making.

Process versus results is an incredibly important distinction to make
when discussing environmental justice. A decision that is seen as
pro-environment (say, transitioning from coal to water power) can still
be environmentally unjust if it is not made through the proper channels.
Currently, environmentalism is dominated by highly educated, White
activists. Indigenous voices are often muted and, even when considered,
viewed as monoliths where all members of the tribe hold the same values.

The main theme of these discussions is actually quite simple: tribal
sovereignty. The Skull Valley Band has the right to agree--and also to
fight against--any decisions that affect them. The key is to accept
their sovereignty while still remembering the context that has put them
in the situation in the first place. Institutional, structural racism
has oppressed many Indigenous peoples, resulting in poverty and a
dispossession of their own land. Even when they exercise sovereignty, it
still exists in the oppressed context that has put them into making the
decision, as "that tribe and tribes in general have never participated
in the decision-making process that has lead to the production of
nuclear waste or that has lead to the absence of alternate means of
economic survival in the desert landscape to which this tribe has been
relocated" (Ishiyama & TallBear, 2001, p. 10).

These problems are symptoms of the cycle of capitalistic exploitation
that creates systems of poverty so people can be exploited. After all,
it's much easier to steal from the hungry than the full. By ignoring the
system and viewing each decision on a case-by-case basis, Native tribes
are put at fault for choosing one of two evils. As put by Keith Lewis of
the Serpent River First Nation, "There is nothing moral about tempting a
starving man with money" (Kamps, 2001).

The project eventually was halted after years of protest from the state
of Utah, environmental groups, and fellow tribe members like Bullcreek.
The argument is much larger than should the project have been completed
or not though. The villainization of tribe members like Bear from
activists ignore the situation that these leaders have been forced to
make decisions in. As Indigenous Environmental Network director Tom
Goldtooth said, "\...The Tribe is not the enemy here, Private Fuel
Storage is. The State needs to look at policies that threaten the Tribes
health and well-being and work to rectify those first." (Kamps, 2001).

Tribes are working to help their place and their people. They've been
pushed into a corner by colonial powers that have systematically stolen
their land, their bodies, and their culture. Critiquing leaders for
choosing one of two bad situations ignores that they've been forced to
choose by these powers. Tribal sovereignty and environmental justice
work hand in hand. To force any Western views onto them is to take their
right of choice. For too long colonial powers have been telling
Indigenous people what is the okay decision. It is their land. It has
always been their land.

The way to fight environmentally dangerous policies like the Skull Creek
Band nuclear dump is not to fight the proposal, but to have fought the
poverty that made the Band an easy target for PFS. Environmental
justice, economic justice, racial justice--they're all the same thing.
Justice is justice. To fight for the world is to fight for nature. To
fight for nature is to fight for people. Until society switches away
from exploitative measures and towards a more holistic, equitable
system, there will always be another nuclear dump. Like a hydra, when
one anti-environment measure dies, three more grow in its place. The
solution is not to win every small battle, but to just win one: the
culture. True environmental justice must respect tribal sovereignty
while addressing the economic inequalities that have lingered for
generations.

**Works Cited**

Hanson, R. D. (2001). An experiment in (toxic) Indian capitalism?: The
skull valley goshutes, new capitalism, and nuclear waste. *PoLAR:
Political and Legal Anthropology Review*, *24*(2), 25--38.
https://doi.org/10.1525/pol.2001.24.2.25

Ishiyama, N., & TallBear, K. (2001). Changing Notions of Environmental
Justice in the Decision to Host a Nuclear Fuel Storage Facility on the
Skull Valley Goshute Reservation.

Kamps, K. (2001, February 15). *Environmental racism, tribal sovereignty
and nuclear waste · Nirs*. NIRS.
https://www.nirs.org/private-fuel-storages-proposed-interim-high-level-nuclear-waste-dumpsite-on-the-reservation-of-skull-valley-goshute-tribe-40-miles-west/

Pancake, A. (2007). *Strange as this weather has been: A novel*.
Shoemaker & Hoard.

Moore, J. W., & Patel, R. (2020). *A history of the world in Seven cheap
things: A guide to capitalism, nature, and the future of the planet*.
Verso Books.

Whyte, K. (2017). Indigenous Climate Change Studies: Indigenizing
Futures, decolonizing the anthropocene. *English Language Notes*,
    *55*(1--2), 153--162. https://doi.org/10.1215/00138282-55.1-2.153
