# The New Book Burning: Banning Critical Race Theory
*Written for **EDUC-102: Issues in Education** with Prof. Chenyu Wang on 12/7/2021*

Every few years, it seems like both American political parties come up
with new buzzwords. In 2016 it was "emails", in 2018 it was "caravan",
and in 2020 it was "freedom". Now, Republicans across the country have
come up with a new term to frighten their constituents: "Critical Race
Theory" (CRT).

According to Education Week, a nonpartisan news organization covering
K-12 education, critical race theory is an academic idea "that race is a
social construct, and that racism is not merely the product of
individual bias or prejudice, but also something embedded in legal
systems and policies." (Sawchuk). At its core, critical race theory
looks to educate students about the systemic injustices present in
America and its history. Critical race theory studies actions like
school segregation, redlining, and gerrymandering that have had long
lasting effects on systemic oppression despite it being decades since
the Civil Rights Act passed.

However, some conservatives have conflated critical race theory with ALL
social justice movements--similarly to how they conflated all the police
brutality protests with Black Lives Matter--and have used it as a
buzzword to signal that something is "woke" and therefore bad. From
diversity training to "cancel culture", some conservatives worldwide
believe that the heart of critical race theory is not learning about our
dark history, but simply blaming all white people for the past actions
of the nation. Just look at this tweet from former British National
Party leader Nick Griffin (also, crop your memes, dude):

[[https://twitter.com/NickGriffinBU/status/1467989827115233288]{.underline}](https://twitter.com/NickGriffinBU/status/1467989827115233288)

In the tweet, Griffin post a picture of a brown bear, black bear, and
polar bear, with text underneath stating, "BROWN BEAR", "BLACK BEAR",
and "RACIST BEAR", captioned "Critical race theory. The actual #racism
afflicting the death pangs of liberalism." This is a common criticism of
critical race theory, saying it is racist against white people and
simply asks white people to take responsibility for racism.

This is unfounded. White people are not being asked to apologize for
systemic oppression, simply to acknowledge its existence. It's not about
saying all white people are racist and need to change, it's about
showing all people that systemic racism is a very real problem that
needs to be addressed. It's about explaining *why* the poverty rate in
2018 among Black people is 20.8% versus 8.1% for white people (Bureau,
U. S. C.). It's about explaining *why* 1 in 3 black men in America are
likely to be imprisoned at some point in their life, compared to 1 in 17
white men ("Mass Incarceration"). It's about explaining *why* the
average graduation rate for white people in the US is 89% yet just 80%
for Black people (*Coe*).

Additionally, conservatives have pushed critical race theory as an
anti-American, anti-democratic, and often "Communist" theory. They
believe that students learning about the United States' often negative
history will turn them, I guess, into revolutionaries who want to
overthrow the government. Their prime example of critical race theory's
anti-patriotic ways are the allegations of racism against America's
founding fathers.

Most proponents of critical race theory wouldn't argue the genius of
someone like Thomas Jefferson. His view of the nation created the
foundation of one of the world's greatest superpowers. However, how can
one read the second paragraph of the Declaration of Independence and not
see the irony? The country's founding document explains that "all men
are created equal", yet many of those who signed their name owned other
human beings at this time. The nation is founded on hypocrisy. Many of
the founding fathers were not great men. Some, it could be argued, were
bad. Acknowledging this isn't anti-America, it isn't attacking the
ideals this country was founded on, it is simply being okay with the
country not being perfect and working to fix it.

What is American about forcing ideals on people? The country was founded
on a violent revolution to free itself from a "tyrannical" regime. How
is wanting to better the nation unamerican? How is pushing ideals that
may differ from the norm unamerican? This is supposed to be the land of
the free. Freedom of speech includes freedom of thought, and that
freedom should be protected. It is not tyrannical to teach our history.
However, it is tyrannical to change our history.

For years, American education has been white washed. Generations of
people have learned an education based on a white person's perspective,
barely touching on slavery outside of an economic factor and instead
only focusing on the rare times in history where the country has created
a positive for Black people. The Emancipation Proclamation,
13^th^-15^th^ amendments, Brown vs. Board of Ed., and the Civil Rights
Movement are taught as the entirety of Black American history. Black
history *is* American history. They shouldn't be separated. That's all
critical race theory looks to do. It simply looks to finally teach
American history as it should be taught--focusing on ALL Americans, not
just those in power.

Despite all of its positives, critical race theory is being fought by
the right as if it's a bigger threat to Americans than the disease that
has killed 800,000. Bills are being passed throughout the nation that
would rip funding from schools that teach critical race theory. One bill
proposed in Wisconsin would prohibit teaching concepts like "equity",
"institutional oppression", and "social justice". In Texas, a new bill
just went into law that bans teachers from discussing "a widely debated
and currently controversial issue of public policy or social affairs.\"
(Garcia). The bill doesn't specify what is a controversial issue, but a
related bill passed made the rounds after a Texas school district
executive said "...make sure that if you have a book on the Holocaust,
that you have one that has an opposing, that has other perspectives.".
If something as evil, ruthless, and fact-laden as the Holocaust can be
deemed "controversial", then there's no telling how far this
governmental overreach of our education system will go.

Republicans' ability to push everything they don't like as
anti-American, Marxist, and revolutionary is an attempt to maintain
power akin to Thomas Jefferson's original view of public education.
Except instead of ensuring only wealthy white men get an education like
Jefferson tried, Republicans are trying to make sure that *everyone*
gets an education *written* by wealthy white men. This allows them to
continue to push an idea of American exceptionalism, and call anyone who
dares criticize their perfect country unamerican.

Critical race theory should not be a controversial curriculum. It's
simply creating an education that looks at American history
unapologetically and unbiased. America has a dark history, but, as
Churchill said, "those that fail to learn from history are doomed to
repeat it.". The only true way to better our country is to acknowledge
that we have problems. We aren't a perfect country and trying to ban
teachings like critical race theory only threatens to move us backwards.

**Works Cited**

> Bureau, US Census. "Income, Poverty and Health Insurance Coverage in
> the United States: 2018." *Census.gov*, 8 Oct. 2021,
> https://www.census.gov/newsroom/press-releases/2019/income-poverty.html#:\~:text=The%20poverty%20rate%20for%20non,not%20statistically%20different%20from%202017.
>
> *Coe - Public High School Graduation Rates*,
> https://nces.ed.gov/programs/coe/indicator/coi.
>
> Garcia, Ariana. "A New \'Critical Race Theory\' Law Just Went into
> Effect in Texas Schools." *Chron*, Chron, 6 Dec. 2021,
> https://www.chron.com/politics/article/Texas-critical-race-theory-law-schools-16678700.php.
>
> Griffin, Nick. "Critical Race Theory. the Actual #Racism Afflicting
> the Death Pangs of Liberalism. Pic.twitter.com/Biqkoponbe." *Twitter*,
> Twitter, 6 Dec. 2021,
> https://twitter.com/NickGriffinBU/status/1467989827115233288.
>
> "Mass Incarceration." *American Civil Liberties Union*,
> https://www.aclu.org/issues/smart-justice/mass-incarceration.
>
> Sawchuk, Stephen. "What Is Critical Race Theory, and Why Is It under
> Attack?" *Education Week*, Education Week, 21 Sept. 2021,
> https://www.edweek.org/leadership/what-is-critical-race-theory-and-why-is-it-under-attack/2021/05.
